GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "laqqaz",
    "url": "http://example.com/test-blog",
    "likes": 5
}